### ISSUE TITLE
Easier way to achieve the small multiples effect

### ISSUE THREAD

**Issue by webbedfeet** [kjhealy/covid#3]
Hi Kieran,

The `gghighlight` package makes the plotting of all the other countries in gray on the same plot much easier. 

For example, I plot death tracks from the JHU data (Twitter: @corona_dt), and created a data frame `deaths_after_10` to keep all countries with at least 10 deaths. To plot the small multiples:
```r
library(tidyverse)
library(gghighlight)
ggplot(deaths_after_10, aes(x=days, y=deaths))+
  geom_line(aes(group=country_region), color='firebrick')+ 
  gghighlight() + 
  facet_wrap(~country_region) + 
  theme_classic() + 
  labs(x = 'Days since 10th death', y = 'Cumulative number of deaths')
```
gets you the following plot
![image](https://user-images.githubusercontent.com/370335/77812859-a8e32180-707a-11ea-9adf-6f3c4d9e38da.png)

Writing here since I figured this would be easiest way to get feedback to you. Happy plotting, and love your book

**Comment by kjhealy** [comment]
Hey, thanks for this! Yeah, I know about `gghighlight` and have used it myself. In this case (for teaching reasons, mostly) I just wanted to do it without that package, just to show what the logic of it is. And thank you for your kind words about the book :)
